### PR TITLE
fix: direct udp bound to session src #971

### LINKED ISSUE #971: direct udp socket  bound to session src address
for direct udp outbound the socket is wrongly bound to session src address.

https://github.com/Watfaq/clash-rs/blob/master/clash-lib%2Fsrc%2Fproxy%2Fdirect%2Fmod.rs#L93-L93

### PR DESCRIPTION
**Pull request by spongebob888**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
Fix #971. 

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ibigbug** [comment]
Thank you. Must have been a typo mistake in the first place.

**Review by ibigbug — APPROVED** [review]

**Comment by spongebob888** [comment]
Yeah. I think so too

**Comment by ibigbug** [comment]
tests seem failing

**Comment by spongebob888** [comment]
It's pretty strange.  I didn't change any tcp related code. And the failure can't be reproduced in my local machine

**Comment by ibigbug** [comment]
I agree. Maybe dns ? I'm bot sure. Will need some time to take a look

**Comment by spongebob888** [comment]
I will take a look later

File: clash-lib/src/app/remote_content_manager/mod.rs [hunk 1]
```diff
@@ -1004,7 +1004,7 @@ mod tests {
         initialize();
         let mut mock_resolver = MockClashResolver::new();
         mock_resolver.expect_resolve().returning(|_, _| {
-            Ok(Some(std::net::IpAddr::V4(Ipv4Addr::new(172, 217, 167, 67))))
```
Comment (ibigbug) [inline clash-lib/src/app/remote_content_manager/mod.rs:1007]: alright, seems the previous Google IP is somehow unreachable

File: clash-lib/src/proxy/direct/mod.rs [hunk 2]
```diff
@@ -89,8 +89,13 @@ impl OutboundHandler for Handler {
         resolver: ThreadSafeDNSResolver,
     ) -> std::io::Result<BoxedChainedDatagram> {
         let family_hint = family_hint_for_session(sess, &resolver).await;
+        let bind_addr = if sess.source.is_ipv4() {
+            "0.0.0.0:0"
+        } else {
+            "[::]:0"
+        };
```
Comment (ibigbug) [inline clash-lib/src/proxy/direct/mod.rs]:
```suggestion
        let bind_addr: std::net::IpAddr = if sess.source.is_ipv4() {
            std::net::Ipv4Addr::UNSPECIFIED.into()
        } else {
            std::net::Ipv6Addr::UNSPECIFIED.into()
        };
```

File: clash-lib/src/proxy/direct/mod.rs [hunk 3]
```diff
@@ -89,8 +89,13 @@ impl OutboundHandler for Handler {
...
         let d = new_udp_socket(
-            Some(sess.source),
+            Some(bind_addr.parse().unwrap()),
```
Comment (ibigbug) [inline clash-lib/src/proxy/direct/mod.rs]:
```suggestion
            Some((bind_addr, 0).into()),
```
